import { Button, TextEdit, GridBox } from "std-widgets.slint";

export component AppWindow inherits Window {
    title: "Calculator";
    in-out property <string> textarea: ""; // Proprietate pentru afișarea textului în zona de text
    in-out property <bool> tfocus;
    callback add_to_text_area(string, string); // Callback pentru adăugarea textului în zona de text
        // TASK: Creează un TextEdit pentru zona de text a calculatorului.
        // HINT: Setează lățimea la 600px și înălțimea la 200px.
    callback text_editing(string);
    width: 600px;
    height: 400px;
    VerticalLayout {
        text_box := TextEdit {
            text: root.textarea;
            // wrap: TextWrap.no-wrap;
            height: 100px;
            horizontal-alignment: TextHorizontalAlignment.center;
            has-focus: root.tfocus;
            edited => {
                text_editing(root.textarea)
            }
        }

        for l in [{ j:0, b:"+", c:"C" }, { j:1, b:"-", c:"(" }, { j:2, b:"*", c:")" }]: HorizontalLayout {
            for i in [1, 2, 3]: // Rectangle {
                Button {
                text: i + l.j * 3;
                clicked => {
                    add_to_text_area(text-box.text, i + l.j * 3)
                }
            }
            Button {
                text: l.b;
                clicked => {
                    add_to_text_area(text-box.text, l.b)
                }
            }

            Button {
                text: l.c;
                clicked => {
                    add_to_text_area(text-box.text, l.c)
                }
            }
        }
        //}
        HorizontalLayout {
            Button {
                text: ".";
                clicked => {
                    add_to_text_area(text-box.text,".");
                }
            }

            Button {
                text: 0;
                clicked => {
                    add_to_text_area(text-box.text,0);
                }
            }

            Button {
                text: "=";
                clicked => {
                    add_to_text_area(text-box.text,"=");
                }
            }

            Button {
                text: "/";
                clicked => {
                    add_to_text_area(text-box.text,"/");
                }
            }

            Button {
                text: "CE";
                clicked => {
                    add_to_text_area(text-box.text,"CE");
                }
            }
        }
    }   
        // TASK: Adaugă alte rânduri pentru cifrele și operatorii rămași, similar cu primul rând.
        // HINT: Creează noi `GridLayout` și adaugă butoane pentru cifrele "4" până la "9", operatorii "*", "-", "/", ".", "Clear" și "=".
}
